version: "3"
services:
  web:
    container_name: python_server
    build: .
    ports:
      - "8008:8008"
    volumes:
      - .:/app
    # Needed for multi-worker image fetching/transforming when training
    shm_size: "2gb"
