version: "3.7"
services:
  web:
    container_name: snake_server
    build:
      context: .
      target: prod
    ports:
      - "8008:8008"
  dev:
    container_name: snake_dev
    build:
      context: .
      target: dev
    ports:
      - "8008:8008"
    # Needed for multi-worker image fetching/transforming when training
    shm_size: "2gb"
